from game.llm.prompts import PERSONAS

# Central database/registry for NPC configuration
NPC_DATA: dict[str, dict] = {
    "player": {
        "name": "Anthony",  # more novel-like than "You"
        "sprite_file": "Actor1.png",
        "sprite_index": 0,
        "face_file": "Actor1.png",
        "face_index": 0,
    },

    # ---------------- Crown's Reach ----------------
    "king": {
        "name": "King Arthur",
        "location": "crowns_reach",
        "sprite_file": "People3.png",
        "sprite_index": 0,
        "face_file": "People3.png",
        "face_index": 0,
        "persona": PERSONAS["king"],
    },
    "father": {
        "name": "Prime Minister Henry",
        "location": "crowns_reach",
        "sprite_file": "People4.png",
        "sprite_index": 4,
        "face_file": "People4.png",
        "face_index": 4,
        "persona": PERSONAS["father"],
    },
    "mage": {
        "name": "Mage Aldous",
        "location": "crowns_reach",
        "sprite_file": "Actor2.png",
        "sprite_index": 4,
        "face_file": "Actor2.png",
        "face_index": 4,
        "persona": PERSONAS["mage"],
    },
    "marquis": {
        "name": "Marquis Percival",
        "location": "crowns_reach",
        "sprite_file": "People3.png",
        "sprite_index": 4,
        "face_file": "People3.png",
        "face_index": 4,
        "persona": PERSONAS["marquis"],
    },
    "barnaby": {
        "name": "Barnaby",
        "location": "crowns_reach",
        "sprite_file": "People1.png",
        "sprite_index": 2,
        "face_file": "People1.png",
        "face_index": 2,
        "persona": PERSONAS["barnaby"],
    },
    "michael": {
        "name": "Guard Michael",
        "location": "crowns_reach",
        "sprite_file": "Actor1.png",
        "sprite_index": 6,
        "face_file": "Actor1.png",
        "face_index": 6,
        "persona": PERSONAS["michael"],
    },

    # ---------------- Tarnstead ----------------
    "cedric": {
        "name": "Lord Cedric",
        "location": "tarnstead",
        "sprite_file": "Actor3.png",
        "sprite_index": 2,
        "face_file": "Actor3.png",
        "face_index": 2,
        "persona": PERSONAS["cedric"],
    },
    "silas": {
        "name": "Silas",
        "location": "tarnstead",
        "sprite_file": "Evil.png",
        "sprite_index": 3,
        "face_file": "Evil.png",
        "face_index": 3,
        "persona": PERSONAS["silas"],
    },
    "grizzly": {
        "name": "Grizzly",
        "location": "tarnstead",
        "sprite_file": "People1.png",
        "sprite_index": 4,
        "face_file": "People1.png",
        "face_index": 4,
        "persona": PERSONAS["grizzly"],
    },
    "brunt": {
        "name": "Brunt",
        "location": "tarnstead",
        "sprite_file": "Evil.png",
        "sprite_index": 1,
        "face_file": "Evil.png",
        "face_index": 1,
        "persona": PERSONAS["brunt"],
    },
    "thorne": {
        "name": "Captain Thorne",
        "location": "tarnstead",
        "sprite_file": "People3.png",
        "sprite_index": 6,
        "face_file": "People3.png",
        "face_index": 6,
        "persona": PERSONAS["thorne"],
    },
    "elara": {
        "name": "Elara",
        "location": "tarnstead",
        "sprite_file": "Actor3.png",
        "sprite_index": 6,
        "face_file": "Actor3.png",
        "face_index": 6,
        "persona": PERSONAS["elara"],
    },
    "deserter": {
        "name": "Deserted Guard",
        "location": "tarnstead",
        "sprite_file": "People3.png",
        "sprite_index": 7,
        "face_file": "People3.png",
        "face_index": 7,
        "persona": PERSONAS["deserter"],
    },
    "courier": {
        "name": "Masked Courier",
        "location": "tarnstead",
        "sprite_file": "Evil.png",
        "sprite_index": 4,
        "face_file": "Evil.png",
        "face_index": 4,
        "persona": PERSONAS["courier"],
    },
}
