
# Central database/registry for NPC configuration
NPC_DATA: dict[str, dict] = {
    "player": {
        "name": "You",
        "sprite_file": "Actor1.png",
        "sprite_index": 0,
        "face_file": "Actor1.png",
        "face_index": 0,
    },
    "king": {
        "name": "The King",
        "sprite_file": "People3.png",
        "sprite_index": 0,
        "face_file": "People3.png",
        "face_index": 0,
        "persona": "You are King Arthur, the rightful ruler of this land. You are arrogant, impatient, and look down on commoners.",
    },
    "father": {
        "name": "The Father",
        "sprite_file": "People4.png",
        "sprite_index": 4,
        "face_file": "People4.png",
        "face_index": 4,
        "persona": "todo",
    },
    "mage": {
        "name": "The Mage",
        "sprite_file": "Actor2.png",
        "sprite_index": 4,
        "face_file": "Actor2.png",
        "face_index": 4,
        "persona": "todo",
    },
    "marquis": {
        "name": "The Marquis",
        "sprite_file": "People3.png",
        "sprite_index": 4,
        "face_file": "People3.png",
        "face_index": 4,
        "persona": "todo",
    },
    "innkeeper": {
        "name": "The Innkeeper",
        "sprite_file": "People1.png",
        "sprite_index": 2,
        "face_file": "People1.png",
        "face_index": 2,
        "persona": "todo",
    },
    "royal_guard": {
        "name": "Royal Guard",
        "sprite_file": "Actor1.png",
        "sprite_index": 6,
        "face_file": "Actor1.png",
        "face_index": 6,
        "persona": "todo",
    },
    "cedric": {
        "name": "Lord Cedric",
        "sprite_file": "Actor3.png",
        "sprite_index": 2,
        "face_file": "Actor3.png",
        "face_index": 2,
        "persona": "todo",
    },
    "sorcerer": {
        "name": "The Sorcerer",
        "sprite_file": "Evil.png",
        "sprite_index": 3,
        "face_file": "Evil.png",
        "face_index": 3,
        "persona": "todo",
    },
    "tavern_keeper": {
        "name": "The Tavern Keeper",
        "sprite_file": "People1.png",
        "sprite_index": 4,
        "face_file": "People1.png",
        "face_index": 4,
        "persona": "todo",
    },
    "bouncer": {
        "name": "The Bouncer",
        "sprite_file": "Evil.png",
        "sprite_index": 1,
        "face_file": "Evil.png",
        "face_index": 1,
        "persona": "todo",
    },
    "captain": {
        "name": "The Captain",
        "sprite_file": "People3.png",
        "sprite_index": 6,
        "face_file": "People3.png",
        "face_index": 6,
        "persona": "todo",
    },
    "smuggler": {
        "name": "The Smuggler",
        "sprite_file": "Actor3.png",
        "sprite_index": 6,
        "face_file": "Actor3.png",
        "face_index": 6,
        "persona": "todo",
    },
    "fugitive_ranger": {
        "name": "Fugitive Ranger",
        "sprite_file": "People3.png",
        "sprite_index": 7,
        "face_file": "People3.png",
        "face_index": 7,
        "persona": "todo",
    },
    "courier": {
        "name": "The Courier",
        "sprite_file": "Evil.png",
        "sprite_index": 4,
        "face_file": "Evil.png",
        "face_index": 4,
        "persona": "todo",
    },
}
